directive @lookup on FIELD_DEFINITION

directive @internal on OBJECT | FIELD_DEFINITION

directive @inaccessible on FIELD_DEFINITION | OBJECT | INTERFACE | UNION | ARGUMENT_DEFINITION | SCALAR | ENUM | ENUM_VALUE | INPUT_OBJECT | INPUT_FIELD_DEFINITION

directive @is(field: FieldSelectionMap!) on ARGUMENT_DEFINITION

directive @require(field: FieldSelectionMap!) on ARGUMENT_DEFINITION

directive @key(fields: FieldSelectionSet!) repeatable on OBJECT | INTERFACE

directive @shareable repeatable on OBJECT | FIELD_DEFINITION

directive @provides(fields: FieldSelectionSet!) on FIELD_DEFINITION

directive @external on FIELD_DEFINITION

directive @override(from: String!) on FIELD_DEFINITION

directive @interfaceObject on OBJECT

directive @implement on FIELD_DEFINITION

type Query {
  productById(id: ID!): Product @lookup
}

type Product @key(fields: "id") {
  id: ID!
}

scalar FieldSelectionMap

scalar FieldSelectionSet