name: CI

run-name: "CI / #${{ github.event.pull_request.number }} / ${{ github.event.pull_request.title }}"

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-and-test:
    name: Build & Test
    uses: ./.github/workflows/build.yml
